{
 "title": "IDrac Dell Server",
 "tags": [ "idrac" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{device_type=\"dell\"},device_type)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{device_type=\"$type\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server basic information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(processorDeviceIndex{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "SystemStatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "globalSystemStatus" }
   ]
  },
  {
   "title": "DISK ISSUES",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{hostname=\"$node\"} == 4"
    }
   ]
  },
  {
   "title": "PS2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "amperageProbeReading{hostname=\"$node\"} > 20"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "temperatureProbeReading/10\n/ ignoring(temperatureProbeLocationName) group_right\ntemperatureProbeLocationName",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemPowerState{hostname=\"$node\"}"
    }
   ]
  },
  {
   "title": "CONTROLLER BATTERY",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{hostname=\"$node\"} != 3"
    }
   ]
  },
  {
   "title": "PS1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{hostname=\"$node\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  { "title": "Server hard disk information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Panel Title",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{hostname=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{hostname=\"$node\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{hostname=\"$node\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{hostname=\"$node\"}"
    }
   ]
  }
 ]
}